SELECT 
  project.name AS project_name,
  project.id AS project_id,
  (SELECT value from UNNEST(labels) WHERE key='team') AS team_label,
  (SELECT value from UNNEST(project.labels) WHERE key='team') AS team,
  (SELECT value from UNNEST(project.labels) WHERE key='environment') AS env,
  (SELECT value from UNNEST(project.labels) WHERE key='tenant') AS tenant,
  (SELECT value from UNNEST(labels) WHERE key='k8s-namespace') AS k8s_namespace,
  (SELECT value from UNNEST(labels) WHERE key='k8s-label/app') AS k8s_app,
  (SELECT value from UNNEST(labels) WHERE key='app') AS app_label,
  (SELECT value from UNNEST(labels) WHERE key='goog-k8s-cluster-name') AS k8s_cluster,
  service.description AS service_description,
  sku.id AS sku_id,
  sku.description AS sku_description,
  resource.global_name AS resource_name,
  usage_start_time,
  usage_end_time,
  usage.amount AS usage_amount,
  usage.unit AS usage_unit,
  cost,
  credits,
  _PARTITIONDATE AS partition_date
FROM `nais-io.nais_billing_regional.gcp_billing_export_resource_v1_014686_D32BB4_68DF8E`